# Generated by Django 5.2.8 on 2025-12-14 18:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calibre_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=500)),
                ('pubdate', models.DateField(blank=True, null=True)),
                ('path', models.CharField(max_length=1000)),
                ('isbn', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['author'],
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_provider', models.CharField(blank=True, choices=[('GEMINI', 'Google Gemini'), ('OPENROUTER', 'OpenRouter')], max_length=20)),
                ('api_key', models.CharField(blank=True, max_length=200)),
                ('extraction_rate_limit_per_minute', models.PositiveIntegerField(default=256)),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configuration',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_name', models.CharField(max_length=50, null=True)),
                ('model_name', models.CharField(max_length=200, null=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('total_chapters', models.PositiveIntegerField(default=0)),
                ('chapters_processed', models.JSONField(default=list)),
                ('extraction_method', models.CharField(choices=[('file', 'File'), ('block', 'Block')], max_length=50, null=True)),
                ('images_in_separate_chapters', models.BooleanField(null=True)),
                ('images_can_be_matched', models.BooleanField(null=True)),
                ('recipes_found', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(default=list)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_reports', to='core.book')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('ingredients', models.JSONField(null=True)),
                ('instructions', models.JSONField(null=True)),
                ('yields', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='core.book')),
                ('extraction_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='core.extractionreport')),
                ('keywords', models.ManyToManyField(blank=True, related_name='recipes', to='core.keyword')),
            ],
            options={
                'ordering': ['book', 'order'],
            },
        ),
        migrations.CreateModel(
            name='RecipeListItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='core.recipe')),
                ('recipe_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.recipelist')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('recipe_list', 'recipe')},
            },
        ),
        migrations.AddField(
            model_name='recipelist',
            name='recipes',
            field=models.ManyToManyField(blank=True, related_name='recipe_lists', through='core.RecipeListItem', to='core.recipe'),
        ),
    ]
