# Generated by Django 5.2.8 on 2025-12-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extractionreport',
            options={'ordering': ['-completed_at']},
        ),
        migrations.AddField(
            model_name='recipelist',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
