# Generated by Django 5.2.8 on 2025-12-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='calibre_added_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
