# Generated by Django 5.2.8 on 2026-01-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_recipelist_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionreport',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('review', 'Awaiting Review'), ('done', 'Completed')], default='running', max_length=20),
        ),
        migrations.AddField(
            model_name='extractionreport',
            name='thread_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
