# Generated by Django 5.2.8 on 2026-05-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_enable_wal_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='ai_provider',
            field=models.CharField(blank=True, choices=[('GEMINI', 'Google Gemini'), ('OPENROUTER', 'OpenRouter'), ('STUB', 'Stub (offline / dev)')], max_length=20),
        ),
    ]
