"""cache the resolved reader position on recipes

Revision ID: 043eb01521db
Revises: c7d8e9f0a1b2
Create Date: 2026-08-09 21:15:20.371911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '043eb01521db'
down_revision: Union[str, Sequence[str], None] = 'c7d8e9f0a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('epub_cfi', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('epub_checked_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('epub_checked_at')
        batch_op.drop_column('epub_cfi')

    # ### end Alembic commands ###
