"""reading queue items

Revision ID: 219faab92061
Revises: 043eb01521db
Create Date: 2026-08-09 21:08:47.862829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '219faab92061'
down_revision: Union[str, Sequence[str], None] = '043eb01521db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_queue_items',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'book_id')
    )
    with op.batch_alter_table('reading_queue_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reading_queue_items_book_id'), ['book_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_queue_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reading_queue_items_book_id'))

    op.drop_table('reading_queue_items')
    # ### end Alembic commands ###
