"""game dismissals

Revision ID: 92e44a5da92d
Revises: 7c1b3a9e5d20
Create Date: 2026-08-22 23:35:19.578547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92e44a5da92d'
down_revision: Union[str, Sequence[str], None] = '7c1b3a9e5d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_dismissals',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('recipe_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recipe_id')
    )
    with op.batch_alter_table('game_dismissals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_dismissals_recipe_id'), ['recipe_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_dismissals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_dismissals_recipe_id'))

    op.drop_table('game_dismissals')
    # ### end Alembic commands ###
