"""book reading progress

Revision ID: aa47490e5991
Revises: d810cc6f7c91
Create Date: 2026-08-08 20:38:12.712142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa47490e5991'
down_revision: Union[str, Sequence[str], None] = 'd810cc6f7c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_readings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('fraction', sa.Float(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'book_id')
    )
    with op.batch_alter_table('book_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_readings_book_id'), ['book_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('book_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_readings_book_id'))

    op.drop_table('book_readings')
    # ### end Alembic commands ###
