"""add config extraction_rate_limit_per_minute

Revision ID: bcc69efeffc5
Revises: 73f5bb9f4b28
Create Date: 2026-06-01 23:31:31.412543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcc69efeffc5'
down_revision: Union[str, Sequence[str], None] = '73f5bb9f4b28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default backfills any existing singleton Config row and satisfies the
    # NOT NULL constraint; the ORM model supplies the same default on insert.
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'extraction_rate_limit_per_minute',
                sa.Integer(),
                nullable=False,
                server_default='256',
            )
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.drop_column('extraction_rate_limit_per_minute')

    # ### end Alembic commands ###
