"""assistant conversations

Revision ID: bf82b8e02704
Revises: fe7863779c3e
Create Date: 2026-08-26 22:40:21.066803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf82b8e02704'
down_revision: Union[str, Sequence[str], None] = 'fe7863779c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_conversations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assistant_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assistant_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('assistant_turns',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['assistant_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assistant_turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assistant_turns_conversation_id'), ['conversation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistant_turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistant_turns_conversation_id'))

    op.drop_table('assistant_turns')
    with op.batch_alter_table('assistant_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistant_conversations_user_id'))

    op.drop_table('assistant_conversations')
    # ### end Alembic commands ###
