"""folded search columns

Revision ID: fe7863779c3e
Revises: 92e44a5da92d
Create Date: 2026-08-26 21:50:31.472541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.text import fold


# revision identifiers, used by Alembic.
revision: str = 'fe7863779c3e'
down_revision: Union[str, Sequence[str], None] = '92e44a5da92d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('title_folded', sa.String(length=500), nullable=False, server_default='')
        )
        batch_op.add_column(
            sa.Column('author_folded', sa.String(length=500), nullable=False, server_default='')
        )

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('name_folded', sa.String(length=500), nullable=False, server_default='')
        )

    bind = op.get_bind()
    books = [
        {'pk': pk, 'title': fold(title), 'author': fold(author)}
        for pk, title, author in bind.execute(sa.text('SELECT id, title, author FROM books'))
    ]
    if books:
        bind.execute(
            sa.text(
                'UPDATE books SET title_folded = :title, author_folded = :author WHERE id = :pk'
            ),
            books,
        )
    recipes = [
        {'pk': pk, 'name': fold(name)}
        for pk, name in bind.execute(sa.text('SELECT id, name FROM recipes'))
    ]
    if recipes:
        bind.execute(sa.text('UPDATE recipes SET name_folded = :name WHERE id = :pk'), recipes)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('name_folded')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('author_folded')
        batch_op.drop_column('title_folded')

    # ### end Alembic commands ###
