from app.services.ai.anthropic import AnthropicProvider
from app.services.ai.base import (
    AIProvider,
    AIResponseError,
    EmbedTask,
    KeywordClassification,
    ModelRole,
    Usage,
)
from app.services.ai.gemini import GeminiProvider
from app.services.ai.openrouter import OpenRouterProvider
from app.services.ai.registry import (
    ResolvedTask,
    add_provider_models,
    ai_ready,
    all_recommendations,
    eligible_providers,
    ensure_provider_configs,
    get_ai_provider,
    get_assistant_provider,
    get_config,
    get_provider_config,
    ocr_ready,
    provider_catalogue,
    provider_requires_api_key,
    recommendation,
    remove_provider_models,
    require_task,
    resolve_embeddings,
    resolve_ingredient_chain,
    resolve_task,
    seed_model_ids,
    set_provider_key,
    set_provider_order,
    set_task_assignment,
    upsert_provider_config,
)
from app.services.ai.stub import StubProvider

__all__ = [
    "AIProvider",
    "AIResponseError",
    "AnthropicProvider",
    "EmbedTask",
    "GeminiProvider",
    "KeywordClassification",
    "ModelRole",
    "OpenRouterProvider",
    "ResolvedTask",
    "StubProvider",
    "Usage",
    "add_provider_models",
    "ai_ready",
    "all_recommendations",
    "eligible_providers",
    "ensure_provider_configs",
    "get_ai_provider",
    "get_assistant_provider",
    "get_config",
    "get_provider_config",
    "ocr_ready",
    "provider_catalogue",
    "provider_requires_api_key",
    "recommendation",
    "remove_provider_models",
    "require_task",
    "resolve_embeddings",
    "resolve_ingredient_chain",
    "resolve_task",
    "seed_model_ids",
    "set_provider_key",
    "set_provider_order",
    "set_task_assignment",
    "upsert_provider_config",
]
